import { useCallback, useEffect, useMemo, useState } from 'react'
import { ArrowDownToLine, ArrowLeft, BookOpen, ChevronRight, ExternalLink, MessageSquareText, Search, Star, Trash2, Upload, UserRound, X } from 'lucide-react'

const formatSize = (bytes) => bytes >= 1024 ** 2 ? `${(bytes / 1024 ** 2).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`
const formatDate = (value) => new Date(value).toLocaleDateString('zh-CN')
const displayName = (person) => person.nickname || person.uploaderDisplay || person.username || person.uploader || '匿名读者'

function Avatar({ person, size = 28 }) {
  return <span className="store-avatar" style={{ '--avatar-size': `${size}px` }}>{person.avatar || person.uploaderAvatar ? <img src={person.avatar || person.uploaderAvatar} alt="" /> : <UserRound size={Math.round(size * .52)} />}</span>
}

const coverDataCache = new Map()
// 有封面时显示 EPUB 真封面，否则回退到传入的占位内容
function CoverMark({ book, children }) {
  const [cover, setCover] = useState(() => coverDataCache.get(book.id) || '')
  useEffect(() => {
    if (!book.hasCover || cover) return undefined
    let cancelled = false
    window.readerAPI?.storeBookCover?.(book.id).then((url) => { coverDataCache.set(book.id, url || ''); if (!cancelled) setCover(url || '') }).catch(() => {})
    return () => { cancelled = true }
  }, [book.id, book.hasCover, cover])
  return cover ? <img className="store-cover-img" src={cover} alt={`《${book.title}》封面`} /> : children
}

export function BookstorePreview({ onOpen }) {
  const [books, setBooks] = useState([])
  useEffect(() => { window.readerAPI?.listStoreBooks({}).then((result) => setBooks(result.books?.slice(0, 5) || [])).catch(() => setBooks([])) }, [])
  return <section className="v-store-preview"><header><div><span>共享书城</span><strong>最近上传</strong></div><button onClick={onOpen}>进入书城 <ChevronRight size={14} /></button></header>{books.length ? <div className="v-store-preview-list">{books.map((book) => <button key={book.id} onClick={onOpen}><i><CoverMark book={book}><b>{book.title.slice(0, 1)}</b><em>{book.format}</em></CoverMark></i><span><strong>{book.title}</strong><small>{book.author || '作者未注明'}</small><small>上传者：{displayName(book)}{book.averageRating ? ` · ★ ${book.averageRating.toFixed(1)}` : ''}</small></span></button>)}</div> : <p>登录后可浏览大家分享的书籍</p>}</section>
}

export default function Bookstore({ onClose, onDownloaded }) {
  const [books, setBooks] = useState([]), [categories, setCategories] = useState([])
  const [query, setQuery] = useState(''), [category, setCategory] = useState(''), [selectedId, setSelectedId] = useState('')
  const [busy, setBusy] = useState(''), [message, setMessage] = useState(''), [upload, setUpload] = useState(null)
  const [rating, setRating] = useState(5), [comment, setComment] = useState('')
  const load = useCallback(async () => { try { const result = await window.readerAPI.listStoreBooks({ q: query, category }); setBooks(result.books || []); setCategories(result.categories || []); setMessage('') } catch (error) { setMessage(error.message || '请先在“用户数据”中登录') } }, [category, query])
  useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer) }, [load])
  const selected = useMemo(() => books.find((book) => book.id === selectedId), [books, selectedId])
  const mine = selected?.reviews?.find((item) => item.mine)
  const openDetail = (book) => { setSelectedId(book.id); const own = book.reviews.find((item) => item.mine); setRating(own?.rating || 5); setComment(own?.comment || '') }
  const run = async (key, action) => { setBusy(key); setMessage(''); try { await action(); await load() } catch (error) { setMessage(error.message || '操作失败') } finally { setBusy('') } }
  const chooseUpload = async () => { const picked = await window.readerAPI.chooseStoreUpload(); if (picked) setUpload({ ...picked, category: categories[0] || '文学' }) }
  const download = (book) => run(`down-${book.id}`, async () => { const local = await window.readerAPI.downloadStoreBook(book); if (local) onDownloaded(local) })
  return <div className="store-overlay" role="dialog" aria-modal="true" aria-label="共享书城"><section className={`store-page ${selected ? 'has-detail' : ''}`}>
    <header className="store-header"><div><span>MOYU COMMONS · PRIVATE LIBRARY</span><h1>{selected ? '书籍详情' : '共享书城'}</h1><p>{selected ? '一本书，以及读过它的人留下的痕迹' : '私人读者共同维护的电子书目录'}</p></div><div className="store-header-actions"><button className="store-web-link" onClick={() => window.readerAPI?.openExternal?.('https://modu.cxnnn.cn/')}><ExternalLink size={14} />打开web版</button><button onClick={onClose} aria-label="关闭书城"><X /></button></div></header>
    {message ? <p className="store-message">{message}</p> : null}
    {selected ? <div className="store-detail"><button className="store-back" onClick={() => setSelectedId('')}><ArrowLeft size={15} />返回书城</button><div className="store-detail-layout">
      <section className="store-detail-book"><div className="store-detail-cover"><CoverMark book={selected}><span>{selected.format}</span><strong>{selected.title}</strong><em>{selected.category}</em></CoverMark></div><div className="store-detail-copy"><span className="store-kicker">{selected.category} · {formatSize(selected.size)}</span><h2>{selected.title}</h2><p className="store-detail-author">{selected.author || '作者未注明'}</p><div className="store-uploader"><Avatar person={selected} size={34} /><span><small>上传者</small><strong>{displayName(selected)}</strong><em>{formatDate(selected.uploadedAt)}</em></span></div><div className="store-detail-rating"><Star fill={selected.averageRating ? 'currentColor' : 'none'} /><strong>{selected.averageRating ? selected.averageRating.toFixed(1) : '—'}</strong><span>{selected.ratingCount ? `${selected.ratingCount} 位读者评分` : '等待第一份评分'}</span></div><button className="store-download-primary" disabled={Boolean(busy)} onClick={() => download(selected)}><ArrowDownToLine size={16} />{busy === `down-${selected.id}` ? '下载中…' : '下载到本机书架'}</button><div className="store-owner-tools">{selected.canManage ? <button onClick={() => { const next = prompt('输入新分类', selected.category); if (next?.trim()) run(`cat-${selected.id}`, () => window.readerAPI.updateStoreBookCategory({ id: selected.id, category: next.trim() })) }}>整理分类</button> : null}<button className="danger" disabled={Boolean(busy)} onClick={() => confirm(`从书城永久删除《${selected.title}》？全部分卷都会删除且不可恢复。`) && run(`delete-${selected.id}`, async () => { await window.readerAPI.deleteStoreBook(selected.id); setSelectedId('') })}><Trash2 size={13} />{busy === `delete-${selected.id}` ? '删除中…' : '删除书籍'}</button></div></div></section>
      <section className="store-review-pane"><header><div><MessageSquareText size={16} /><h3>读者评价</h3><span>{selected.reviews.length}</span></div><p>评分将汇总为本书的平均分</p></header><div className="store-review-compose"><span>我的评分</span><div className="store-stars">{[1,2,3,4,5].map((value) => <button key={value} aria-label={`${value} 星`} className={value <= rating ? 'active' : ''} onClick={() => setRating(value)}><Star fill="currentColor" /></button>)}</div><textarea value={comment} onChange={(event) => setComment(event.target.value)} maxLength={1200} placeholder="写下读完后的感受，也可以只留下评分…" /><div><small>{comment.length}/1200</small>{mine ? <button className="danger" onClick={() => run('review-delete', () => window.readerAPI.deleteStoreReview(selected.id))}>删除我的评价</button> : null}<button className="primary" disabled={Boolean(busy)} onClick={() => run('review', () => window.readerAPI.reviewStoreBook({ id: selected.id, rating, comment }))}>{busy === 'review' ? '保存中…' : '发布评价'}</button></div></div><div className="store-reviews">{selected.reviews.length ? selected.reviews.map((item) => <article key={item.id}><Avatar person={item} size={30} /><div><header><strong>{displayName(item)}</strong><span>{item.rating} <Star size={11} fill="currentColor" /></span><time>{formatDate(item.createdAt)}</time></header><p>{item.comment || '只留下了评分'}</p></div></article>) : <div className="store-review-empty"><BookOpen size={25} /><strong>还没有读者评价</strong><span>读完后回来，留下第一份书评。</span></div>}</div></section>
    </div></div> : <><div className="store-tools"><label><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索书名、作者或上传者" /></label><button className="store-upload-button" onClick={chooseUpload}><Upload size={15} />上传书籍</button></div><nav className="store-categories"><button className={!category ? 'active' : ''} onClick={() => setCategory('')}>全部</button>{categories.map((item) => <button key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</nav><div className="store-grid">{books.map((book, index) => <article className="store-book" key={book.id} onClick={() => openDetail(book)}><div className="store-book-mark"><CoverMark book={book}><span>{book.format}</span><strong>{book.category}</strong></CoverMark></div><div className="store-book-main"><span className="store-book-index">{String(index + 1).padStart(2, '0')}</span><h2>{book.title}</h2><p>{book.author || '作者未注明'}</p><div className="store-uploader-compact"><Avatar person={book} size={22} /><small>{displayName(book)} · {formatDate(book.uploadedAt)}</small></div><div className="store-rating"><Star size={14} fill={book.averageRating ? 'currentColor' : 'none'} />{book.averageRating ? `${book.averageRating.toFixed(1)}（${book.ratingCount}人）` : '暂无评分'}</div></div><ChevronRight className="store-card-arrow" size={16} /></article>)}</div>{!books.length && !message ? <div className="store-empty"><strong>这里还没有书</strong><span>上传第一本 TXT 或 EPUB，建立私人书友间的共享书架。</span></div> : null}</>}
  </section>{upload ? <div className="store-subdialog"><section><h2>上传到书城</h2><label>书名<input value={upload.title} onChange={(event) => setUpload({ ...upload, title: event.target.value })} /></label><label>作者<input value={upload.author} onChange={(event) => setUpload({ ...upload, author: event.target.value })} /></label><label>分类<input list="store-category-list" value={upload.category} onChange={(event) => setUpload({ ...upload, category: event.target.value })} /><datalist id="store-category-list">{categories.map((item) => <option value={item} key={item} />)}</datalist></label><small>{formatSize(upload.size)} · 服务器按内容去重，重复书籍会提示已由谁上传</small>{message ? <p className="store-message">{message}</p> : null}<footer><button onClick={() => setUpload(null)}>取消</button><button className="primary" disabled={!upload.title.trim() || !upload.category.trim() || Boolean(busy)} onClick={() => run('upload', async () => { await window.readerAPI.uploadStoreBook(upload); setUpload(null) })}>{busy === 'upload' ? '上传中…' : '确认上传'}</button></footer></section></div> : null}</div>
}
